apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: hello1
spec:
  steps:
    - name: hello1
      image: ubuntu
      command:
        - echo
      args:
        - "Hello $(params.username)!"
  params:
  - name: username
    type: string