apiVersion: apps/v1  
kind: Deployment
metadata:
  name: httpserver-deploy
spec:
  selector: 
    matchLabels:
      app: httpserver  
  replicas: 2
  template:
    metadata:
      labels:
        app: httpserver
    spec:
      containers:
      - name: httpserver-cluster
        image: zhaoxiaoyong/httpserver:v1.0
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 1
            memory: 500Mi
          limits:
            cpu: 2
            memory: 1024Mi
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 5
          successThreshold: 2    
      terminationGracePeriodSeconds: 60
