kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jenkins-pvc-claim
  namespace: jenkins
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 2Gi
